/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: 
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef GUIADAPTOR_H
#define GUIADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface local.MainWindow
 */
class GuiAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "local.MainWindow")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"local.MainWindow\">\n"
"    <signal name=\"changeCurrentAvatar\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </signal>\n"
"    <method name=\"displayCorrectImage\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"user\"/>\n"
"    </method>\n"
"    <method name=\"hideImage\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"user\"/>\n"
"    </method>\n"
"    <method name=\"setImageInLabel\"/>\n"
"    <method name=\"recordedStart\"/>\n"
"  </interface>\n"
        "")
public:
    GuiAdaptor(QObject *parent);
    virtual ~GuiAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void displayCorrectImage(const QString &user);
    void hideImage(const QString &user);
    void recordedStart();
    void setImageInLabel();
Q_SIGNALS: // SIGNALS
    void changeCurrentAvatar(const QString &in0);
};

#endif
